ALTER TABLE `Client`
	ADD COLUMN `status` VARCHAR(191) NOT NULL DEFAULT 'Prospect',
	ADD COLUMN `phone` VARCHAR(191) NULL,
	ADD COLUMN `address` VARCHAR(191) NULL,
	ADD COLUMN `city` VARCHAR(191) NULL,
	ADD COLUMN `state` VARCHAR(191) NULL,
	ADD COLUMN `zipCode` VARCHAR(191) NULL,
	DROP COLUMN `source`;
