ALTER TABLE `SystemSetting`
	ADD COLUMN `googleMapsApiKey` TEXT NULL,
	ADD COLUMN `openAiApiKey` TEXT NULL,
	ADD COLUMN `smtpHost` VARCHAR(191) NULL,
	ADD COLUMN `smtpPort` INTEGER NULL,
	ADD COLUMN `smtpSecure` BOOLEAN NOT NULL DEFAULT false,
	ADD COLUMN `smtpUser` VARCHAR(191) NULL,
	ADD COLUMN `smtpPass` TEXT NULL,
	ADD COLUMN `smtpFromName` VARCHAR(191) NULL,
	ADD COLUMN `smtpFromEmail` VARCHAR(191) NULL;
