const SKILLS_TO_SEED = [
	{ name: 'JavaScript', category: 'Engineering' },
	{ name: 'TypeScript', category: 'Engineering' },
	{ name: 'React', category: 'Engineering' },
	{ name: 'Next.js', category: 'Engineering' },
	{ name: 'Node.js', category: 'Engineering' },
	{ name: 'Express.js', category: 'Engineering' },
	{ name: 'Python', category: 'Engineering' },
	{ name: 'Java', category: 'Engineering' },
	{ name: 'C#', category: 'Engineering' },
	{ name: '.NET', category: 'Engineering' },
	{ name: 'REST APIs', category: 'Engineering' },
	{ name: 'GraphQL', category: 'Engineering' },
	{ name: 'Microservices', category: 'Engineering' },
	{ name: 'SQL', category: 'Data' },
	{ name: 'MySQL', category: 'Data' },
	{ name: 'PostgreSQL', category: 'Data' },
	{ name: 'Data Analysis', category: 'Data' },
	{ name: 'Data Visualization', category: 'Data' },
	{ name: 'Power BI', category: 'Data' },
	{ name: 'Tableau', category: 'Data' },
	{ name: 'ETL Pipelines', category: 'Data' },
	{ name: 'Data Warehousing', category: 'Data' },
	{ name: 'Forecasting', category: 'Data' },
	{ name: 'AWS', category: 'Cloud/DevOps' },
	{ name: 'Azure', category: 'Cloud/DevOps' },
	{ name: 'Google Cloud Platform', category: 'Cloud/DevOps' },
	{ name: 'Docker', category: 'Cloud/DevOps' },
	{ name: 'Kubernetes', category: 'Cloud/DevOps' },
	{ name: 'Terraform', category: 'Cloud/DevOps' },
	{ name: 'CI/CD', category: 'Cloud/DevOps' },
	{ name: 'Linux Administration', category: 'Cloud/DevOps' },
	{ name: 'Monitoring & Observability', category: 'Cloud/DevOps' },
	{ name: 'Network Security', category: 'Security/Compliance' },
	{ name: 'Identity & Access Management', category: 'Security/Compliance' },
	{ name: 'Risk Assessment', category: 'Security/Compliance' },
	{ name: 'Incident Response', category: 'Security/Compliance' },
	{ name: 'SOC 2 Compliance', category: 'Security/Compliance' },
	{ name: 'HIPAA Compliance', category: 'Security/Compliance' },
	{ name: 'SOX Compliance', category: 'Security/Compliance' },
	{ name: 'Internal Audit', category: 'Security/Compliance' },
	{ name: 'Project Management', category: 'Business/Operations' },
	{ name: 'Program Management', category: 'Business/Operations' },
	{ name: 'Business Analysis', category: 'Business/Operations' },
	{ name: 'Process Improvement', category: 'Business/Operations' },
	{ name: 'Stakeholder Management', category: 'Business/Operations' },
	{ name: 'Change Management', category: 'Business/Operations' },
	{ name: 'Vendor Management', category: 'Business/Operations' },
	{ name: 'Customer Success', category: 'Business/Operations' },
	{ name: 'Accounting', category: 'Finance/Accounting' },
	{ name: 'Financial Reporting', category: 'Finance/Accounting' },
	{ name: 'Financial Analysis', category: 'Finance/Accounting' },
	{ name: 'Budgeting', category: 'Finance/Accounting' },
	{ name: 'Cost Accounting', category: 'Finance/Accounting' },
	{ name: 'Payroll Processing', category: 'Finance/Accounting' },
	{ name: 'Accounts Payable', category: 'Finance/Accounting' },
	{ name: 'Accounts Receivable', category: 'Finance/Accounting' },
	{ name: 'Tax Compliance', category: 'Finance/Accounting' },
	{ name: 'Benefits Administration', category: 'HR/People' },
	{ name: 'Employee Relations', category: 'HR/People' },
	{ name: 'Talent Acquisition', category: 'HR/People' },
	{ name: 'Sourcing', category: 'HR/People' },
	{ name: 'Interviewing', category: 'HR/People' },
	{ name: 'Performance Management', category: 'HR/People' },
	{ name: 'Compensation Planning', category: 'HR/People' },
	{ name: 'Onboarding', category: 'HR/People' },
	{ name: 'Contract Negotiation', category: 'Legal/Compliance' },
	{ name: 'Legal Research', category: 'Legal/Compliance' },
	{ name: 'Corporate Governance', category: 'Legal/Compliance' },
	{ name: 'Regulatory Affairs', category: 'Legal/Compliance' },
	{ name: 'Policy Development', category: 'Legal/Compliance' },
	{ name: 'Litigation Support', category: 'Legal/Compliance' },
	{ name: 'Account Management', category: 'Sales/Marketing' },
	{ name: 'Business Development', category: 'Sales/Marketing' },
	{ name: 'Lead Generation', category: 'Sales/Marketing' },
	{ name: 'Pipeline Management', category: 'Sales/Marketing' },
	{ name: 'Consultative Selling', category: 'Sales/Marketing' },
	{ name: 'CRM Management', category: 'Sales/Marketing' },
	{ name: 'Salesforce', category: 'Sales/Marketing' },
	{ name: 'HubSpot', category: 'Sales/Marketing' },
	{ name: 'Digital Marketing', category: 'Sales/Marketing' },
	{ name: 'Content Marketing', category: 'Sales/Marketing' },
	{ name: 'SEO', category: 'Sales/Marketing' },
	{ name: 'Supply Chain Management', category: 'Manufacturing/Industrial' },
	{ name: 'Inventory Management', category: 'Manufacturing/Industrial' },
	{ name: 'Procurement', category: 'Manufacturing/Industrial' },
	{ name: 'Production Planning', category: 'Manufacturing/Industrial' },
	{ name: 'Lean Manufacturing', category: 'Manufacturing/Industrial' },
	{ name: 'Quality Assurance', category: 'Manufacturing/Industrial' },
	{ name: 'Six Sigma', category: 'Manufacturing/Industrial' },
	{ name: 'Warehouse Operations', category: 'Manufacturing/Industrial' },
	{ name: 'Patient Care Coordination', category: 'Healthcare' },
	{ name: 'Case Management', category: 'Healthcare' },
	{ name: 'Clinical Documentation', category: 'Healthcare' },
	{ name: 'EMR/EHR Systems', category: 'Healthcare' },
	{ name: 'Medical Coding', category: 'Healthcare' },
	{ name: 'Medical Billing', category: 'Healthcare' },
	{ name: 'Utilization Review', category: 'Healthcare' },
	{ name: 'Patient Scheduling', category: 'Healthcare' }
];

module.exports = {
	SKILLS_TO_SEED
};
